# Generated by Django 4.1.1 on 2022-09-29 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idarticulo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('mano_de_obra', models.FloatField(blank=True, null=True)),
                ('otrosgastos', models.FloatField(blank=True, null=True)),
                ('costo_material', models.FloatField(blank=True, null=True)),
                ('cantidad_material', models.FloatField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('porciento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['idarticulo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('nit', models.FloatField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', models.CharField(blank=True, max_length=45, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('porciento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['idempleado'],
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('idenvios', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha_envio')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['idenvios'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOrdentrabajo',
            fields=[
                ('idordentrabajo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'EstadoOrdentrabajo',
                'verbose_name_plural': 'EstadoOrdentrabajos',
                'ordering': ['idordentrabajo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('idestado_venta', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'EstadoVenta',
                'verbose_name_plural': 'EstadoVentas',
                'ordering': ['idestado_venta'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['idmaterial'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraMaterial',
            fields=[
                ('idorden_compra_material', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('total', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'OrdenCompraMaterial',
                'verbose_name_plural': 'OrdenCompraMateriales',
                'ordering': ['idorden_compra_material'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['idpersona'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedores', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['idproveedores'],
            },
        ),
        migrations.CreateModel(
            name='Puestoempleado',
            fields=[
                ('idpuestoempleado', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Puestoempleado',
                'verbose_name_plural': 'Puestoempleados',
                'ordering': ['idpuestoempleado'],
            },
        ),
        migrations.CreateModel(
            name='Tipoinventario',
            fields=[
                ('idtipoinventario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Tipoinventario',
                'verbose_name_plural': 'Tipoinventarios',
                'ordering': ['idtipoinventario'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('hora_fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha_venta')),
                ('articulo', models.ForeignKey(db_column='articulo', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventaarticulocotizacion', to='AppFerrus.cotizacion')),
                ('cliente', models.OneToOneField(db_column='cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventaclientecotizacion', to='AppFerrus.cotizacion')),
                ('cotizacion', models.OneToOneField(db_column='idcotizacion', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventacotizacion', to='AppFerrus.cotizacion')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['idventa'],
            },
        ),
        migrations.CreateModel(
            name='Ordendetrabajo',
            fields=[
                ('idordendetrabajo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('definicion', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_empieza', models.DateField(blank=True, null=True)),
                ('fecha_termina', models.DateField(blank=True, null=True)),
                ('correlativo', models.IntegerField(blank=True, null=True)),
                ('empleado_idempleado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ordendetrabajoventaempleado', to='AppFerrus.empleado')),
                ('estado', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ordendetrabajoestado', to='AppFerrus.estadoordentrabajo')),
                ('venta_articulo', models.ForeignKey(db_column='articulo', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ordendetrabajoarticulo', to='AppFerrus.venta')),
                ('venta_cliente', models.OneToOneField(db_column='cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ordendetrabajocliente', to='AppFerrus.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('inventario_material', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventariomaterial', to='AppFerrus.material')),
                ('tipo', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventariotipo', to='AppFerrus.tipoinventario')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['idinventario'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='empleadopersona', to='AppFerrus.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puestoempleado',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='empleadopuesto', to='AppFerrus.puestoempleado'),
        ),
        migrations.CreateModel(
            name='Detcotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cotizacion')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.material'),
        ),
    ]
