# Generated by Django 3.2.9 on 2022-10-24 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('mano_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('otrosgastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('porciento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('stockenviado', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('nit', models.FloatField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', models.CharField(blank=True, max_length=45, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('porciento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOrdentrabajo',
            fields=[
                ('idordentrabajo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'EstadoOrdentrabajo',
                'verbose_name_plural': 'EstadoOrdentrabajos',
                'ordering': ['idordentrabajo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'EstadoVenta',
                'verbose_name_plural': 'EstadoVentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalcompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidadcompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Puestoempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Puestoempleado',
                'verbose_name_plural': 'Puestoempleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre Usuario')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha_venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente')),
                ('estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.estadoventa')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ordendetrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente')),
                ('estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.estadoordentrabajo')),
                ('persona', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.persona')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha_venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidadcompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('proveedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.proveedores')),
            ],
            options={
                'verbose_name': 'OrdenCompraMaterial',
                'verbose_name_plural': 'OrdenCompraMateriales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=45, null=True)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente')),
                ('persona', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.persona')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='empleadopersona', to='AppFerrus.persona')),
                ('puestoempleado', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='empleadopuesto', to='AppFerrus.puestoempleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detordentrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('ordendetrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.ordendetrabajo')),
            ],
            options={
                'verbose_name': 'Detalle orden de trabajo',
                'verbose_name_plural': 'Detalle ordenes de trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.CharField(blank=True, max_length=45, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('totalcompra', models.IntegerField(default=0)),
                ('cantidadcompra', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('material', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.material')),
                ('orden_compra_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.ordencompramaterial')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detenvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('envios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.envios')),
            ],
            options={
                'verbose_name': 'Detalle envio',
                'verbose_name_plural': 'Detalle envios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detcotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cotizacion')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detarticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.material')),
            ],
            options={
                'verbose_name': 'Detalle articulo',
                'verbose_name_plural': 'Detalle articulos',
                'ordering': ['id'],
            },
        ),
    ]
