# Generated by Django 3.2.9 on 2022-10-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_admin',
            field=models.BooleanField(default=True),
        ),
    ]
