# Generated by Django 4.1.1 on 2022-10-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0002_material_stock_ordencompramaterial_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
