# Generated by Django 4.1.1 on 2022-10-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0003_alter_cliente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='material',
        ),
        migrations.CreateModel(
            name='Detarticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.material')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
            },
        ),
    ]
