# Generated by Django 4.1.1 on 2022-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0004_remove_articulo_material_detarticulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detarticulo',
            options={'ordering': ['id'], 'verbose_name': 'Detalle articulo', 'verbose_name_plural': 'Detalle articulos'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='mano_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='otrosgastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
