# Generated by Django 4.1.1 on 2022-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0005_alter_detarticulo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
