# Generated by Django 4.1.1 on 2022-10-01 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0006_alter_articulo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
