# Generated by Django 4.1.1 on 2022-10-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0007_articulo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='empleado_idempleado',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.empleado'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.estadoordentrabajo'),
        ),
    ]
