# Generated by Django 4.1.1 on 2022-10-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0008_remove_ordendetrabajo_empleado_idempleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='venta_cliente',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.estadoordentrabajo'),
        ),
    ]
