# Generated by Django 4.1.1 on 2022-10-02 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0009_remove_ordendetrabajo_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cliente'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
