# Generated by Django 4.1.1 on 2022-10-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0011_remove_ordendetrabajo_empleado_envios_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='correlativo',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='venta_articulo',
        ),
        migrations.CreateModel(
            name='Detordentrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('idordendetrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.cotizacion')),
            ],
            options={
                'verbose_name': 'Detalle orden de trabajo',
                'verbose_name_plural': 'Detalle ordenes de trabajo',
                'ordering': ['id'],
            },
        ),
    ]
