# Generated by Django 4.1.1 on 2022-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0013_alter_detordentrabajo_idordendetrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detarticulo',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
