# Generated by Django 4.1.1 on 2022-10-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0015_articulo_stock_detventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='hora_fecha',
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(db_column='articulo', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventaarticulocotizacion', to='AppFerrus.estadoventa'),
        ),
    ]
