# Generated by Django 4.1.1 on 2022-10-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0016_remove_venta_articulo_remove_venta_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detenvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('idenvios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.envios')),
            ],
            options={
                'verbose_name': 'Detalle envio',
                'verbose_name_plural': 'Detalle envios',
                'ordering': ['id'],
            },
        ),
    ]
