# Generated by Django 4.1.1 on 2022-10-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0017_detenvios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.OneToOneField(db_column='cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventaclientecotizacion', to='AppFerrus.cliente'),
        ),
        migrations.CreateModel(
            name='DetOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo')),
                ('idorden_compra_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.ordencompramaterial')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizaciones',
                'ordering': ['id'],
            },
        ),
    ]
