# Generated by Django 3.2.9 on 2022-10-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0019_ordencompramaterial_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendetrabajo',
            old_name='fecha_empieza',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='fecha_termina',
        ),
    ]
