# Generated by Django 3.2.9 on 2022-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0020_auto_20221014_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='stock',
            new_name='stockenviado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad_material',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='costo_material',
        ),
        migrations.AddField(
            model_name='detventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
