# Generated by Django 3.2.9 on 2022-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0021_auto_20221017_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
