# Generated by Django 3.2.9 on 2022-10-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0022_articulo_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Tipoinventario',
        ),
    ]
