# Generated by Django 3.2.9 on 2022-10-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0025_alter_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detordencompra',
            name='articulo',
        ),
        migrations.AddField(
            model_name='detordencompra',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.material'),
        ),
    ]
