# Generated by Django 3.2.9 on 2022-10-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0026_auto_20221018_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='detordencompra',
            name='articulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo'),
        ),
    ]
