# Generated by Django 3.2.9 on 2022-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0028_auto_20221018_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='detordencompra',
            name='cantidadcompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detordencompra',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detordencompra',
            name='totalcompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
