# Generated by Django 3.2.9 on 2022-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0029_auto_20221019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detordencompra',
            name='cantidadcompra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detordencompra',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detordencompra',
            name='totalcompra',
            field=models.IntegerField(default=0),
        ),
    ]
