# Generated by Django 3.2.9 on 2022-10-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0030_auto_20221019_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompramaterial',
            name='articulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.articulo'),
        ),
    ]
