# Generated by Django 3.2.9 on 2022-10-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0032_alter_detordencompra_cant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detordencompra',
            name='articulo',
        ),
    ]
