# Generated by Django 3.2.9 on 2022-10-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0033_remove_detordencompra_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompramaterial',
            name='descripcion',
        ),
    ]
